version: '3.2'

services:

#================================================================================================
# GOLANG
#================================================================================================
  golang:
    restart: always
    build:
      context: .
    ports:
      - "9101:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/golang:/go
    privileged: true
    environment:
      - GOLANG_VERSION=${GOLANG_VERSION}
